// Dataset global de aeropuertos y rutas para el prototipo FlightConnections

const AIRPORTS = [
  // --- North America (USA) ---
  { iata: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "United States", lat: 40.6413, lng: -73.7781 },
  { iata: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "United States", lat: 33.9416, lng: -118.4085 },
  { iata: "MIA", name: "Miami International Airport", city: "Miami", country: "United States", lat: 25.7959, lng: -80.2870 },
  { iata: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "United States", lat: 37.6213, lng: -122.3790 },
  { iata: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "United States", lat: 41.9742, lng: -87.9073 },
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "United States", lat: 33.6407, lng: -84.4277 },
  { iata: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "United States", lat: 32.8998, lng: -97.0403 },
  { iata: "IAH", name: "George Bush Intercontinental Airport", city: "Houston", country: "United States", lat: 29.9902, lng: -95.3368 },
  { iata: "DEN", name: "Denver International Airport", city: "Denver", country: "United States", lat: 39.8561, lng: -104.6737 },
  { iata: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", country: "United States", lat: 47.4502, lng: -122.3088 },
  { iata: "BOS", name: "Logan International Airport", city: "Boston", country: "United States", lat: 42.3656, lng: -71.0096 },
  { iata: "LAS", name: "Harry Reid International Airport", city: "Las Vegas", country: "United States", lat: 36.0840, lng: -115.1537 },
  { iata: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix", country: "United States", lat: 33.4342, lng: -112.0080 },
  { iata: "MCO", name: "Orlando International Airport", city: "Orlando", country: "United States", lat: 28.4312, lng: -81.3081 },
  { iata: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", country: "United States", lat: 39.8729, lng: -75.2437 },
  { iata: "DTW", name: "Detroit Metropolitan Airport", city: "Detroit", country: "United States", lat: 42.2162, lng: -83.3554 },
  { iata: "MSP", name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis", country: "United States", lat: 44.8848, lng: -93.2223 },
  { iata: "HNL", name: "Daniel K. Inouye International Airport", city: "Honolulu", country: "United States", lat: 21.3187, lng: -157.9225 },
  { iata: "EWR", name: "Newark Liberty International Airport", city: "New York / Newark", country: "United States", lat: 40.6895, lng: -74.1745 },

  // --- Canada ---
  { iata: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada", lat: 43.6777, lng: -79.6248 },
  { iata: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "Canada", lat: 49.1967, lng: -123.1815 },
  { iata: "YUL", name: "Montréal-Trudeau International Airport", city: "Montreal", country: "Canada", lat: 45.4706, lng: -73.7408 },
  { iata: "YYC", name: "Calgary International Airport", city: "Calgary", country: "Canada", lat: 51.1215, lng: -114.0076 },

  // --- Mexico & Central America & Caribbean ---
  { iata: "MEX", name: "Benito Juárez International Airport", city: "Mexico City", country: "Mexico", lat: 19.4363, lng: -99.0721 },
  { iata: "CUN", name: "Cancún International Airport", city: "Cancún", country: "Mexico", lat: 21.0365, lng: -86.8771 },
  { iata: "GDL", name: "Guadalajara International Airport", city: "Guadalajara", country: "Mexico", lat: 20.5218, lng: -103.3112 },
  { iata: "PTY", name: "Tocumen International Airport", city: "Panama City", country: "Panama", lat: 9.0714, lng: -79.3834 },
  { iata: "SJO", name: "Juan Santamaría International Airport", city: "San José", country: "Costa Rica", lat: 9.9939, lng: -84.2088 },
  { iata: "SAL", name: "El Salvador International Airport", city: "San Salvador", country: "El Salvador", lat: 13.4409, lng: -89.0557 },
  { iata: "HAV", name: "José Martí International Airport", city: "Havana", country: "Cuba", lat: 22.9892, lng: -82.4091 },
  { iata: "SDQ", name: "Las Américas International Airport", city: "Santo Domingo", country: "Dominican Republic", lat: 18.4297, lng: -69.6689 },
  { iata: "PUJ", name: "Punta Cana International Airport", city: "Punta Cana", country: "Dominican Republic", lat: 18.5674, lng: -68.3634 },
  { iata: "SJU", name: "Luis Muñoz Marín International Airport", city: "San Juan", country: "Puerto Rico", lat: 18.4394, lng: -66.0018 },

  // --- South America ---
  { iata: "GRU", name: "São Paulo/Guarulhos International Airport", city: "São Paulo", country: "Brazil", lat: -23.4356, lng: -46.4731 },
  { iata: "GIG", name: "Rio de Janeiro/Galeão International Airport", city: "Rio de Janeiro", country: "Brazil", lat: -22.8089, lng: -43.2436 },
  { iata: "BSB", name: "Brasília International Airport", city: "Brasília", country: "Brazil", lat: -15.8692, lng: -47.9208 },
  { iata: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "Argentina", lat: -34.8222, lng: -58.5358 },
  { iata: "COR", name: "Ingeniero Ambrosio Taravella International Airport", city: "Córdoba", country: "Argentina", lat: -31.3236, lng: -64.2081 },
  { iata: "ASU", name: "Silvio Pettirossi International Airport", city: "Asunción", country: "Paraguay", lat: -25.2400, lng: -57.5190 },
  { iata: "MVD", name: "Carrasco International Airport", city: "Montevideo", country: "Uruguay", lat: -34.8384, lng: -56.0305 },
  { iata: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "Chile", lat: -33.3930, lng: -70.7858 },
  { iata: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "Colombia", lat: 4.7016, lng: -74.1469 },
  { iata: "MDE", name: "José María Córdova International Airport", city: "Medellín", country: "Colombia", lat: 6.1645, lng: -75.4231 },
  { iata: "CLO", name: "Alfonso Bonilla Aragón International Airport", city: "Cali", country: "Colombia", lat: 3.5432, lng: -76.3816 },
  { iata: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "Peru", lat: -12.0219, lng: -77.1143 },
  { iata: "UIO", name: "Mariscal Sucre International Airport", city: "Quito", country: "Ecuador", lat: -0.1292, lng: -78.3575 },
  { iata: "GYE", name: "José Joaquín de Olmedo International Airport", city: "Guayaquil", country: "Ecuador", lat: -2.1574, lng: -79.8836 },
  { iata: "VVI", name: "Viru Viru International Airport", city: "Santa Cruz", country: "Bolivia", lat: -17.6448, lng: -63.1354 },
  { iata: "LPB", name: "El Alto International Airport", city: "La Paz", country: "Bolivia", lat: -16.5133, lng: -68.1923 },

  // --- Europe ---
  { iata: "LHR", name: "London Heathrow Airport", city: "London", country: "United Kingdom", lat: 51.4700, lng: -0.4543 },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", lat: 53.3537, lng: -2.2750 },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", lat: 55.9500, lng: -3.3725 },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland", lat: 53.4264, lng: -6.2499 },
  { iata: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France", lat: 49.0097, lng: 2.5479 },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", lat: 50.0379, lng: 8.5622 },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "Germany", lat: 48.3537, lng: 11.7750 },
  { iata: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid", country: "Spain", lat: 40.4839, lng: -3.5680 },
  { iata: "BCN", name: "Josep Tarradellas Barcelona-El Prat Airport", city: "Barcelona", country: "Spain", lat: 41.2974, lng: 2.0833 },
  { iata: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands", lat: 52.3105, lng: 4.7683 },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium", lat: 50.9010, lng: 4.4856 },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", lat: 47.4582, lng: 8.5555 },
  { iata: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria", lat: 48.1103, lng: 16.5697 },
  { iata: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome", country: "Italy", lat: 41.8003, lng: 12.2389 },
  { iata: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy", lat: 45.6301, lng: 8.7255 },
  { iata: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal", lat: 38.7742, lng: -9.1342 },
  { iata: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece", lat: 37.9356, lng: 23.9484 },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark", lat: 55.6180, lng: 12.6508 },
  { iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden", lat: 59.6498, lng: 17.9238 },
  { iata: "OSL", name: "Oslo Airport", city: "Oslo", country: "Norway", lat: 60.1975, lng: 11.1004 },
  { iata: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "Finland", lat: 60.3172, lng: 24.9633 },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland", lat: 52.1672, lng: 20.9679 },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic", lat: 50.1008, lng: 14.2600 },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", lat: 41.2751, lng: 28.7519 },
  { iata: "DME", name: "Domodedovo International Airport", city: "Moscow", country: "Russia", lat: 55.4088, lng: 37.9061 },

  // --- Middle East ---
  { iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "United Arab Emirates", lat: 25.2532, lng: 55.3657 },
  { iata: "AUH", name: "Zayed International Airport", city: "Abu Dhabi", country: "United Arab Emirates", lat: 24.4330, lng: 54.6511 },
  { iata: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar", lat: 25.2611, lng: 51.5650 },
  { iata: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia", lat: 24.9576, lng: 46.6988 },
  { iata: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia", lat: 21.6796, lng: 39.1565 },
  { iata: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "Israel", lat: 32.0055, lng: 34.8854 },

  // --- Asia ---
  { iata: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore", lat: 1.3644, lng: 103.9915 },
  { iata: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan", lat: 35.5494, lng: 139.7798 },
  { iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan", lat: 35.7720, lng: 140.3929 },
  { iata: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan", lat: 34.4320, lng: 135.2304 },
  { iata: "ICN", name: "Seoul Incheon International Airport", city: "Seoul", country: "South Korea", lat: 37.4602, lng: 126.4407 },
  { iata: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China", lat: 40.0799, lng: 116.5971 },
  { iata: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China", lat: 31.1443, lng: 121.8083 },
  { iata: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong", lat: 22.3080, lng: 113.9185 },
  { iata: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei", country: "Taiwan", lat: 25.0797, lng: 121.2342 },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand", lat: 13.6900, lng: 100.7501 },
  { iata: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia", lat: 2.7456, lng: 101.7099 },
  { iata: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam", lat: 10.8188, lng: 106.6518 },
  { iata: "HAN", name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam", lat: 21.2212, lng: 105.8072 },
  { iata: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines", lat: 14.5086, lng: 121.0194 },
  { iata: "CGK", name: "Soekarno–Hatta International Airport", city: "Jakarta", country: "Indonesia", lat: -6.1256, lng: 106.6559 },
  { iata: "DPS", name: "Ngurah Rai (Bali) International Airport", city: "Denpasar", country: "Indonesia", lat: -8.7482, lng: 115.1672 },
  { iata: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi", country: "India", lat: 28.5562, lng: 77.1000 },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India", lat: 19.0896, lng: 72.8656 },
  { iata: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", country: "India", lat: 13.1986, lng: 77.7066 },
  { iata: "SZX", name: "Shenzhen Bao'an International Airport", city: "Shenzhen", country: "China", lat: 22.6393, lng: 113.8107 },

  // --- Africa ---
  { iata: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "South Africa", lat: -26.1367, lng: 28.2411 },
  { iata: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "South Africa", lat: -33.9711, lng: 18.6021 },
  { iata: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya", lat: -1.3192, lng: 36.9275 },
  { iata: "ADD", name: "Addis Ababa Bole International Airport", city: "Addis Ababa", country: "Ethiopia", lat: 8.9778, lng: 38.7993 },
  { iata: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt", lat: 30.1219, lng: 31.4056 },
  { iata: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "Morocco", lat: 33.3675, lng: -7.5898 },
  { iata: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "Algeria", lat: 36.6910, lng: 3.2154 },
  { iata: "TUN", name: "Tunis-Carthage International Airport", city: "Tunis", country: "Tunisia", lat: 36.8510, lng: 10.2272 },
  { iata: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria", lat: 6.5774, lng: 3.3212 },
  { iata: "DKR", name: "Blaise Diagne International Airport", city: "Dakar", country: "Senegal", lat: 14.6710, lng: -17.0733 },

  // --- Oceania ---
  { iata: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia", lat: -33.9461, lng: 151.1772 },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia", lat: -37.6690, lng: 144.8410 },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia", lat: -27.3842, lng: 153.1175 },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "Australia", lat: -31.9403, lng: 115.9668 },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand", lat: -37.0082, lng: 174.7850 }
];

// Rutas directas (declaradas una sola vez por par; la lógica de la app las tratará como bidireccionales)
const ROUTES = [
  // --- Conexiones de Norteamérica (EE.UU. y Canadá) ---
  ["JFK", "LHR"], ["JFK", "LAX"], ["JFK", "MIA"], ["JFK", "GRU"], ["JFK", "FRA"], ["JFK", "CDG"], ["JFK", "DXB"], ["JFK", "SFO"], ["JFK", "ORD"], ["JFK", "ATL"], ["JFK", "YYZ"],
  ["JFK", "DFW"], ["JFK", "DEN"], ["JFK", "DOH"], ["JFK", "FCO"], ["JFK", "LIS"], ["JFK", "BOS"], ["JFK", "MAD"], ["JFK", "BCN"], ["JFK", "DUB"], ["JFK", "MUC"], ["JFK", "ZRH"],
  ["JFK", "AMS"], ["JFK", "HND"], ["JFK", "ICN"], ["JFK", "TLV"], ["JFK", "SJU"], ["JFK", "SDQ"], ["JFK", "PUJ"], ["JFK", "AUH"], ["JFK", "SIN"], ["JFK", "AKL"], ["JFK", "MNL"],
  ["EWR", "SIN"], ["EWR", "LHR"], ["EWR", "FRA"], ["EWR", "CDG"], ["EWR", "TLV"], ["EWR", "HND"], ["EWR", "DEL"], ["EWR", "BOM"], ["EWR", "SFO"], ["EWR", "LAX"],
  ["LAX", "HND"], ["LAX", "NRT"], ["LAX", "SYD"], ["LAX", "MEL"], ["LAX", "HNL"], ["LAX", "SFO"], ["LAX", "ORD"], ["LAX", "MEX"], ["LAX", "GDL"], ["LAX", "YVR"], ["LAX", "LHR"], ["LAX", "SCL"],
  ["LAX", "ICN"], ["LAX", "HKG"], ["LAX", "DFW"], ["LAX", "DEN"], ["LAX", "SEA"], ["LAX", "PTY"], ["LAX", "ZRH"], ["LAX", "CDG"], ["LAX", "FRA"], ["LAX", "TPE"], ["LAX", "PVG"], ["LAX", "AKL"],
  ["LAX", "BOS"], ["LAX", "LAS"], ["LAX", "PHX"], ["LAX", "MCO"], ["LAX", "IAH"], ["LAX", "MNL"], ["LAX", "SIN"],
  ["MIA", "GRU"], ["MIA", "GIG"], ["MIA", "BSB"], ["MIA", "EZE"], ["MIA", "COR"], ["MIA", "ASU"], ["MIA", "MVD"], ["MIA", "BOG"], ["MIA", "MDE"], ["MIA", "CLO"], ["MIA", "MEX"], ["MIA", "CUN"],
  ["MIA", "LHR"], ["MIA", "MAD"], ["MIA", "BCN"], ["MIA", "CDG"], ["MIA", "FRA"], ["MIA", "SCL"], ["MIA", "LIM"], ["MIA", "UIO"], ["MIA", "GYE"], ["MIA", "VVI"], ["MIA", "PTY"], ["MIA", "SJO"],
  ["MIA", "SAL"], ["MIA", "HAV"], ["MIA", "SDQ"], ["MIA", "PUJ"], ["MIA", "SJU"], ["MIA", "LIS"], ["MIA", "FCO"], ["MIA", "CMN"], ["MIA", "DOH"], ["MIA", "ORD"], ["MIA", "ATL"], ["MIA", "IAH"],
  ["MIA", "DFW"], ["MIA", "BOS"],
  ["SFO", "HNL"], ["SFO", "HND"], ["SFO", "NRT"], ["SFO", "YVR"], ["SFO", "ICN"], ["SFO", "HKG"], ["SFO", "TPE"], ["SFO", "PVG"], ["SFO", "SEA"], ["SFO", "DEN"], ["SFO", "LHR"], ["SFO", "FRA"],
  ["SFO", "CDG"], ["SFO", "SIN"], ["SFO", "SYD"], ["SFO", "AKL"], ["SFO", "LAS"], ["SFO", "PHX"], ["SFO", "BOS"], ["SFO", "BLR"], ["SFO", "DEL"], ["SFO", "BOM"],
  ["ORD", "YYZ"], ["ORD", "YUL"], ["ORD", "ATL"], ["ORD", "DFW"], ["ORD", "DEN"], ["ORD", "SEA"], ["ORD", "CUN"], ["ORD", "LHR"], ["ORD", "FRA"], ["ORD", "CDG"], ["ORD", "HND"], ["ORD", "DUB"],
  ["ORD", "BOS"], ["ORD", "LAS"], ["ORD", "PHX"], ["ORD", "MCO"], ["ORD", "DTW"], ["ORD", "MSP"], ["ORD", "MEX"],
  ["ATL", "YYZ"], ["ATL", "YUL"], ["ATL", "AMS"], ["ATL", "DFW"], ["ATL", "DEN"], ["ATL", "CDG"], ["ATL", "LHR"], ["ATL", "FRA"], ["ATL", "MEX"], ["ATL", "CUN"], ["ATL", "PTY"], ["ATL", "BOG"],
  ["ATL", "GRU"], ["ATL", "EZE"], ["ATL", "SJU"], ["ATL", "MCO"], ["ATL", "BOS"], ["ATL", "DTW"], ["ATL", "MSP"],
  ["DFW", "MEX"], ["DFW", "CUN"], ["DFW", "GDL"], ["DFW", "HND"], ["DFW", "NRT"], ["DFW", "ICN"], ["DFW", "LHR"], ["DFW", "FRA"], ["DFW", "CDG"], ["DFW", "MAD"], ["DFW", "DEN"], ["DFW", "IAH"],
  ["DFW", "LAS"], ["DFW", "PHX"], ["DFW", "SEA"], ["DFW", "GRU"], ["DFW", "EZE"], ["DFW", "BOG"], ["DFW", "LIM"], ["DFW", "SCL"], ["DFW", "DOH"], ["DFW", "DXB"], ["DFW", "MEL"], ["DFW", "BNE"], ["DFW", "SYD"], ["DFW", "AKL"],
  ["IAH", "MEX"], ["IAH", "CUN"], ["IAH", "PTY"], ["IAH", "BOG"], ["IAH", "LIM"], ["IAH", "EZE"], ["IAH", "GRU"], ["IAH", "SCL"], ["IAH", "SJO"], ["IAH", "SAL"], ["IAH", "LHR"], ["IAH", "FRA"],
  ["IAH", "AMS"], ["IAH", "DXB"], ["IAH", "DOH"], ["IAH", "HND"], ["IAH", "DEN"], ["IAH", "SEA"], ["IAH", "LAS"], ["IAH", "MCO"], ["IAH", "SYD"], ["IAH", "AKL"],
  ["DEN", "SEA"], ["DEN", "LHR"], ["DEN", "FRA"], ["DEN", "HND"], ["DEN", "NRT"], ["DEN", "CUN"], ["DEN", "YYC"], ["DEN", "PHX"], ["DEN", "LAS"],
  ["SEA", "YVR"], ["SEA", "YYC"], ["SEA", "HNL"], ["SEA", "HND"], ["SEA", "NRT"], ["SEA", "ICN"], ["SEA", "TPE"], ["SEA", "LHR"], ["SEA", "CDG"], ["SEA", "FRA"], ["SEA", "AMS"], ["SEA", "DUB"],
  ["BOS", "LHR"], ["BOS", "CDG"], ["BOS", "FRA"], ["BOS", "DUB"], ["BOS", "LIS"], ["BOS", "MAD"], ["BOS", "FCO"], ["BOS", "AMS"], ["BOS", "DOH"], ["BOS", "DXB"], ["BOS", "YYZ"], ["BOS", "YUL"],
  ["LAS", "LHR"], ["LAS", "FRA"], ["LAS", "MEX"], ["LAS", "YVR"], ["LAS", "YYZ"], ["LAS", "PHX"],
  ["PHX", "LHR"], ["PHX", "MEX"], ["PHX", "CUN"], ["PHX", "YYZ"], ["PHX", "YVR"], ["PHX", "YYC"],
  ["MCO", "LHR"], ["MCO", "FRA"], ["MCO", "CDG"], ["MCO", "MAN"], ["MCO", "BOG"], ["MCO", "PTY"], ["MCO", "SJU"], ["MCO", "SDQ"], ["MCO", "CUN"],
  ["PHL", "LHR"], ["PHL", "CDG"], ["PHL", "FRA"], ["PHL", "MAD"], ["PHL", "FCO"], ["PHL", "DUB"], ["PHL", "CUN"], ["PHL", "SJU"],
  ["DTW", "AMS"], ["DTW", "CDG"], ["DTW", "FRA"], ["DTW", "LHR"], ["DTW", "HND"], ["DTW", "ICN"], ["DTW", "PVG"],
  ["MSP", "AMS"], ["MSP", "CDG"], ["MSP", "LHR"], ["MSP", "HND"], ["MSP", "ICN"], ["MSP", "CUN"],
  ["HNL", "HND"], ["HNL", "NRT"], ["HNL", "ICN"], ["HNL", "SYD"], ["HNL", "AKL"], ["HNL", "YVR"],

  // --- Conexiones de Canadá ---
  ["YYZ", "FRA"], ["YYZ", "MUC"], ["YYZ", "LHR"], ["YYZ", "LGW"], ["YYZ", "CDG"], ["YYZ", "AMS"], ["YYZ", "DUB"], ["YYZ", "LIS"], ["YYZ", "MAD"], ["YYZ", "BCN"], ["YYZ", "FCO"], ["YYZ", "ATL"],
  ["YYZ", "YVR"], ["YYZ", "YUL"], ["YYZ", "YYC"], ["YYZ", "HND"], ["YYZ", "ICN"], ["YYZ", "HKG"], ["YYZ", "DEL"], ["YYZ", "DXB"], ["YYZ", "DOH"], ["YYZ", "TLV"], ["YYZ", "BOG"], ["YYZ", "GRU"],
  ["YYZ", "PTY"], ["YYZ", "CUN"], ["YYZ", "PUJ"],
  ["YVR", "HND"], ["YVR", "NRT"], ["YVR", "KIX"], ["YVR", "ICN"], ["YVR", "HKG"], ["YVR", "TPE"], ["YVR", "PVG"], ["YVR", "SYD"], ["YVR", "BNE"], ["YVR", "AKL"], ["YVR", "LHR"], ["YVR", "FRA"],
  ["YVR", "CDG"], ["YVR", "AMS"], ["YVR", "YUL"], ["YVR", "YYC"], ["YVR", "MEX"], ["YVR", "CUN"],
  ["YUL", "CDG"], ["YUL", "LHR"], ["YUL", "FRA"], ["YUL", "GVA"], ["YUL", "BRU"], ["YUL", "FCO"], ["YUL", "MAD"], ["YUL", "BCN"], ["YUL", "LIS"], ["YUL", "AMS"], ["YUL", "DOH"], ["YUL", "CMN"],
  ["YUL", "ALG"], ["YUL", "MEX"], ["YUL", "CUN"], ["YUL", "PUJ"], ["YUL", "SJU"], ["YUL", "BOG"], ["YUL", "YYC"],
  ["YYC", "LHR"], ["YYC", "FRA"], ["YYC", "AMS"], ["YYC", "CDG"], ["YYC", "NRT"], ["YYC", "CUN"],

  // --- Conexiones de México, Centroamérica y Caribe ---
  ["MEX", "SCL"], ["MEX", "PTY"], ["MEX", "LIM"], ["MEX", "CUN"], ["MEX", "GDL"], ["MEX", "BOG"], ["MEX", "MDE"], ["MEX", "UIO"], ["MEX", "GYE"], ["MEX", "SJO"], ["MEX", "SAL"], ["MEX", "HAV"],
  ["MEX", "SDQ"], ["MEX", "SJU"], ["MEX", "EZE"], ["MEX", "GRU"], ["MEX", "MAD"], ["MEX", "BCN"], ["MEX", "CDG"], ["MEX", "LHR"], ["MEX", "FRA"], ["MEX", "AMS"], ["MEX", "FCO"], ["MEX", "NRT"],
  ["MEX", "ICN"], ["MEX", "SZX"],
  ["CUN", "PTY"], ["CUN", "BOG"], ["CUN", "MDE"], ["CUN", "LIM"], ["CUN", "SJO"], ["CUN", "EZE"], ["CUN", "GRU"], ["CUN", "SCL"], ["CUN", "MAD"], ["CUN", "BCN"], ["CUN", "CDG"], ["CUN", "FRA"],
  ["CUN", "LHR"], ["CUN", "MAN"], ["CUN", "AMS"], ["CUN", "LIS"], ["CUN", "ZRH"], ["CUN", "GDL"],
  ["GDL", "PTY"], ["GDL", "BOG"], ["GDL", "MAD"],
  ["PTY", "BOG"], ["PTY", "MDE"], ["PTY", "CLO"], ["PTY", "LIM"], ["PTY", "SCL"], ["PTY", "EZE"], ["PTY", "COR"], ["PTY", "ASU"], ["PTY", "MVD"], ["PTY", "GRU"], ["PTY", "GIG"], ["PTY", "BSB"],
  ["PTY", "UIO"], ["PTY", "GYE"], ["PTY", "VVI"], ["PTY", "SJO"], ["PTY", "SAL"], ["PTY", "HAV"], ["PTY", "SDQ"], ["PTY", "PUJ"], ["PTY", "SJU"], ["PTY", "MAD"], ["PTY", "CDG"], ["PTY", "AMS"],
  ["PTY", "FRA"], ["PTY", "IST"],
  ["SJO", "BOG"], ["SJO", "LIM"], ["SJO", "MAD"], ["SJO", "FRA"], ["SJO", "CDG"], ["SJO", "LHR"], ["SJO", "SAL"], ["SJO", "SDQ"],
  ["SAL", "BOG"], ["SAL", "LIM"], ["SAL", "MAD"],
  ["HAV", "MAD"], ["HAV", "CDG"], ["HAV", "FRA"], ["HAV", "BOG"], ["HAV", "SDQ"],
  ["SDQ", "MAD"], ["SDQ", "BOG"], ["SDQ", "SJU"], ["SDQ", "PUJ"],
  ["PUJ", "MAD"], ["PUJ", "BCN"], ["PUJ", "CDG"], ["PUJ", "FRA"], ["PUJ", "LHR"], ["PUJ", "ZRH"], ["PUJ", "BOG"], ["PUJ", "GRU"], ["PUJ", "EZE"], ["PUJ", "SCL"], ["PUJ", "LIM"],
  ["SJU", "MAD"], ["SJU", "BOG"],

  // --- Conexiones de Sudamérica (Latinoamérica Sur) ---
  ["GRU", "EZE"], ["GRU", "COR"], ["GRU", "ASU"], ["GRU", "MVD"], ["GRU", "SCL"], ["GRU", "LIM"], ["GRU", "BOG"], ["GRU", "MDE"], ["GRU", "UIO"], ["GRU", "GYE"], ["GRU", "VVI"], ["GRU", "GIG"],
  ["GRU", "BSB"], ["GRU", "MAD"], ["GRU", "BCN"], ["GRU", "LIS"], ["GRU", "CDG"], ["GRU", "FRA"], ["GRU", "MUC"], ["GRU", "LHR"], ["GRU", "AMS"], ["GRU", "FCO"], ["GRU", "MXP"], ["GRU", "ZRH"],
  ["GRU", "IST"], ["GRU", "DXB"], ["GRU", "DOH"], ["GRU", "AUH"], ["GRU", "JNB"], ["GRU", "ADD"], ["GRU", "LOS"], ["GRU", "TLV"],
  ["GIG", "EZE"], ["GIG", "COR"], ["GIG", "MVD"], ["GIG", "SCL"], ["GIG", "LIM"], ["GIG", "BOG"], ["GIG", "BSB"], ["GIG", "LIS"], ["GIG", "MAD"], ["GIG", "CDG"], ["GIG", "FRA"], ["GIG", "LHR"],
  ["GIG", "AMS"], ["GIG", "FCO"], ["GIG", "DXB"], ["GIG", "DOH"],
  ["BSB", "EZE"], ["BSB", "LIS"], ["BSB", "BOG"], ["BSB", "LIM"], ["BSB", "SCL"],
  ["EZE", "COR"], ["EZE", "ASU"], ["EZE", "MVD"], ["EZE", "SCL"], ["EZE", "LIM"], ["EZE", "BOG"], ["EZE", "MDE"], ["EZE", "UIO"], ["EZE", "GYE"], ["EZE", "VVI"], ["EZE", "MAD"], ["EZE", "BCN"],
  ["EZE", "FCO"], ["EZE", "CDG"], ["EZE", "FRA"], ["EZE", "LHR"], ["EZE", "AMS"], ["EZE", "IST"], ["EZE", "DXB"], ["EZE", "DOH"], ["EZE", "ADD"],
  ["COR", "ASU"], ["COR", "MVD"], ["COR", "SCL"], ["COR", "LIM"], ["COR", "BOG"], ["COR", "MAD"],
  ["ASU", "MVD"], ["ASU", "SCL"], ["ASU", "LIM"], ["ASU", "BOG"], ["ASU", "VVI"], ["ASU", "MAD"],
  ["MVD", "SCL"], ["MVD", "LIM"], ["MVD", "BOG"], ["MVD", "MAD"],
  ["SCL", "LIM"], ["SCL", "BOG"], ["SCL", "MDE"], ["SCL", "UIO"], ["SCL", "GYE"], ["SCL", "VVI"], ["SCL", "LPB"], ["SCL", "MAD"], ["SCL", "BCN"], ["SCL", "CDG"], ["SCL", "LHR"], ["SCL", "FRA"],
  ["SCL", "SYD"], ["SCL", "MEL"], ["SCL", "AKL"],
  ["BOG", "MDE"], ["BOG", "CLO"], ["BOG", "LIM"], ["BOG", "UIO"], ["BOG", "GYE"], ["BOG", "VVI"], ["BOG", "LPB"], ["BOG", "MAD"], ["BOG", "BCN"], ["BOG", "CDG"], ["BOG", "LHR"], ["BOG", "FRA"],
  ["BOG", "AMS"], ["BOG", "IST"], ["BOG", "DXB"],
  ["MDE", "LIM"], ["MDE", "UIO"], ["MDE", "GYE"], ["MDE", "MAD"],
  ["CLO", "LIM"], ["CLO", "GYE"], ["CLO", "MAD"],
  ["LIM", "UIO"], ["LIM", "GYE"], ["LIM", "VVI"], ["LIM", "LPB"], ["LIM", "MAD"], ["LIM", "BCN"], ["LIM", "CDG"], ["LIM", "AMS"],
  ["UIO", "GYE"], ["UIO", "MAD"], ["UIO", "AMS"],
  ["GYE", "MAD"], ["GYE", "AMS"],
  ["VVI", "LPB"], ["VVI", "MAD"],

  // --- Conexiones de Europa ---
  ["LHR", "CDG"], ["LHR", "FRA"], ["LHR", "MUC"], ["LHR", "AMS"], ["LHR", "BRU"], ["LHR", "MAD"], ["LHR", "BCN"], ["LHR", "FCO"], ["LHR", "MXP"], ["LHR", "LIS"], ["LHR", "ATH"], ["LHR", "ZRH"],
  ["LHR", "VIE"], ["LHR", "DUB"], ["LHR", "CPH"], ["LHR", "ARN"], ["LHR", "OSL"], ["LHR", "HEL"], ["LHR", "WAW"], ["LHR", "PRG"], ["LHR", "IST"], ["LHR", "MAN"], ["LHR", "EDI"], ["LHR", "DXB"],
  ["LHR", "AUH"], ["LHR", "DOH"], ["LHR", "RUH"], ["LHR", "JED"], ["LHR", "TLV"], ["LHR", "SIN"], ["LHR", "HND"], ["LHR", "NRT"], ["LHR", "KIX"], ["LHR", "ICN"], ["LHR", "HKG"], ["LHR", "BKK"],
  ["LHR", "KUL"], ["LHR", "SGN"], ["LHR", "DEL"], ["LHR", "BOM"], ["LHR", "PEK"], ["LHR", "PVG"], ["LHR", "JNB"], ["LHR", "CPT"], ["LHR", "NBO"], ["LHR", "ADD"], ["LHR", "CAI"], ["LHR", "CMN"],
  ["LHR", "ALG"], ["LHR", "TUN"], ["LHR", "LOS"], ["LHR", "PER"], ["LHR", "SYD"], ["LHR", "MEL"],
  ["CDG", "FRA"], ["CDG", "MUC"], ["CDG", "AMS"], ["CDG", "BRU"], ["CDG", "MAD"], ["CDG", "BCN"], ["CDG", "FCO"], ["CDG", "MXP"], ["CDG", "LIS"], ["CDG", "ATH"], ["CDG", "ZRH"], ["CDG", "VIE"],
  ["CDG", "DUB"], ["CDG", "CPH"], ["CDG", "ARN"], ["CDG", "OSL"], ["CDG", "HEL"], ["CDG", "WAW"], ["CDG", "PRG"], ["CDG", "IST"], ["CDG", "MAN"], ["CDG", "EDI"], ["CDG", "DXB"], ["CDG", "AUH"],
  ["CDG", "DOH"], ["CDG", "RUH"], ["CDG", "JED"], ["CDG", "TLV"], ["CDG", "SIN"], ["CDG", "HND"], ["CDG", "NRT"], ["CDG", "ICN"], ["CDG", "HKG"], ["CDG", "BKK"], ["CDG", "SGN"], ["CDG", "HAN"],
  ["CDG", "DEL"], ["CDG", "BOM"], ["CDG", "PEK"], ["CDG", "PVG"], ["CDG", "JNB"], ["CDG", "CPT"], ["CDG", "NBO"], ["CDG", "ADD"], ["CDG", "CAI"], ["CDG", "CMN"], ["CDG", "ALG"], ["CDG", "TUN"],
  ["CDG", "LOS"], ["CDG", "DKR"],
  ["FRA", "MUC"], ["FRA", "AMS"], ["FRA", "BRU"], ["FRA", "MAD"], ["FRA", "BCN"], ["FRA", "FCO"], ["FRA", "MXP"], ["FRA", "LIS"], ["FRA", "ATH"], ["FRA", "ZRH"], ["FRA", "VIE"], ["FRA", "DUB"],
  ["FRA", "CPH"], ["FRA", "ARN"], ["FRA", "OSL"], ["FRA", "HEL"], ["FRA", "WAW"], ["FRA", "PRG"], ["FRA", "IST"], ["FRA", "MAN"], ["FRA", "EDI"], ["FRA", "DXB"], ["FRA", "AUH"], ["FRA", "DOH"],
  ["FRA", "RUH"], ["FRA", "JED"], ["FRA", "TLV"], ["FRA", "SIN"], ["FRA", "HND"], ["FRA", "NRT"], ["FRA", "KIX"], ["FRA", "ICN"], ["FRA", "HKG"], ["FRA", "TPE"], ["FRA", "BKK"], ["FRA", "KUL"],
  ["FRA", "SGN"], ["FRA", "DEL"], ["FRA", "BOM"], ["FRA", "PEK"], ["FRA", "PVG"], ["FRA", "JNB"], ["FRA", "CPT"], ["FRA", "NBO"], ["FRA", "ADD"], ["FRA", "CAI"], ["FRA", "CMN"], ["FRA", "ALG"],
  ["FRA", "TUN"], ["FRA", "LOS"],
  ["MUC", "AMS"], ["MUC", "BRU"], ["MUC", "MAD"], ["MUC", "BCN"], ["MUC", "FCO"], ["MUC", "MXP"], ["MUC", "LIS"], ["MUC", "ATH"], ["MUC", "ZRH"], ["MUC", "VIE"], ["MUC", "DUB"], ["MUC", "CPH"],
  ["MUC", "ARN"], ["MUC", "OSL"], ["MUC", "HEL"], ["MUC", "WAW"], ["MUC", "PRG"], ["MUC", "IST"], ["MUC", "DXB"], ["MUC", "DOH"], ["MUC", "RUH"], ["MUC", "JED"], ["MUC", "TLV"], ["MUC", "SIN"],
  ["MUC", "HND"], ["MUC", "ICN"], ["MUC", "HKG"], ["MUC", "BKK"], ["MUC", "DEL"], ["MUC", "BOM"], ["MUC", "PEK"], ["MUC", "PVG"], ["MUC", "JNB"], ["MUC", "CPT"], ["MUC", "CAI"],
  ["MAD", "BCN"], ["MAD", "LIS"], ["MAD", "FCO"], ["MAD", "MXP"], ["MAD", "AMS"], ["MAD", "BRU"], ["MAD", "ZRH"], ["MAD", "VIE"], ["MAD", "ATH"], ["MAD", "DUB"], ["MAD", "CPH"], ["MAD", "ARN"],
  ["MAD", "OSL"], ["MAD", "HEL"], ["MAD", "WAW"], ["MAD", "PRG"], ["MAD", "IST"], ["MAD", "MAN"], ["MAD", "EDI"], ["MAD", "DXB"], ["MAD", "AUH"], ["MAD", "DOH"], ["MAD", "RUH"], ["MAD", "JED"],
  ["MAD", "TLV"], ["MAD", "CMN"], ["MAD", "ALG"], ["MAD", "TUN"], ["MAD", "CAI"], ["MAD", "DKR"], ["MAD", "PEK"], ["MAD", "PVG"], ["MAD", "HKG"],
  ["BCN", "LIS"], ["BCN", "FCO"], ["BCN", "MXP"], ["BCN", "AMS"], ["BCN", "BRU"], ["BCN", "ZRH"], ["BCN", "VIE"], ["BCN", "ATH"], ["BCN", "DUB"], ["BCN", "CPH"], ["BCN", "ARN"], ["BCN", "OSL"],
  ["BCN", "HEL"], ["BCN", "WAW"], ["BCN", "PRG"], ["BCN", "IST"], ["BCN", "MAN"], ["BCN", "EDI"], ["BCN", "DXB"], ["BCN", "AUH"], ["BCN", "DOH"], ["BCN", "RUH"], ["BCN", "JED"], ["BCN", "TLV"],
  ["BCN", "CMN"], ["BCN", "ALG"], ["BCN", "TUN"], ["BCN", "CAI"], ["BCN", "ICN"], ["BCN", "SIN"],
  ["AMS", "BRU"], ["AMS", "ZRH"], ["AMS", "VIE"], ["AMS", "FCO"], ["AMS", "MXP"], ["AMS", "LIS"], ["AMS", "ATH"], ["AMS", "DUB"], ["AMS", "CPH"], ["AMS", "ARN"], ["AMS", "OSL"], ["AMS", "HEL"],
  ["AMS", "WAW"], ["AMS", "PRG"], ["AMS", "IST"], ["AMS", "MAN"], ["AMS", "EDI"], ["AMS", "DXB"], ["AMS", "AUH"], ["AMS", "DOH"], ["AMS", "RUH"], ["AMS", "JED"], ["AMS", "TLV"], ["AMS", "SIN"],
  ["AMS", "HND"], ["AMS", "NRT"], ["AMS", "KIX"], ["AMS", "ICN"], ["AMS", "HKG"], ["AMS", "TPE"], ["AMS", "BKK"], ["AMS", "KUL"], ["AMS", "CGK"], ["AMS", "DEL"], ["AMS", "BOM"], ["AMS", "PEK"],
  ["AMS", "PVG"], ["AMS", "JNB"], ["AMS", "CPT"], ["AMS", "NBO"], ["AMS", "ADD"], ["AMS", "CAI"], ["AMS", "CMN"], ["AMS", "LOS"],
  ["BRU", "ZRH"], ["BRU", "VIE"], ["BRU", "FCO"], ["BRU", "MXP"], ["BRU", "LIS"], ["BRU", "ATH"], ["BRU", "DUB"], ["BRU", "CPH"], ["BRU", "ARN"], ["BRU", "OSL"], ["BRU", "HEL"], ["BRU", "WAW"],
  ["BRU", "PRG"], ["BRU", "IST"], ["BRU", "DXB"], ["BRU", "AUH"], ["BRU", "DOH"], ["BRU", "TLV"], ["BRU", "BKK"], ["BRU", "PEK"], ["BRU", "CAI"], ["BRU", "CMN"], ["BRU", "ALG"],
  ["ZRH", "VIE"], ["ZRH", "FCO"], ["ZRH", "MXP"], ["ZRH", "LIS"], ["ZRH", "ATH"], ["ZRH", "DUB"], ["ZRH", "CPH"], ["ZRH", "ARN"], ["ZRH", "OSL"], ["ZRH", "HEL"], ["ZRH", "WAW"], ["ZRH", "PRG"],
  ["ZRH", "IST"], ["ZRH", "MAN"], ["ZRH", "DXB"], ["ZRH", "AUH"], ["ZRH", "DOH"], ["ZRH", "RUH"], ["ZRH", "JED"], ["ZRH", "TLV"], ["ZRH", "SIN"], ["ZRH", "HND"], ["ZRH", "NRT"], ["ZRH", "ICN"],
  ["ZRH", "HKG"], ["ZRH", "BKK"], ["ZRH", "DEL"], ["ZRH", "BOM"], ["ZRH", "PEK"], ["ZRH", "PVG"], ["ZRH", "JNB"], ["ZRH", "CPT"], ["ZRH", "NBO"], ["ZRH", "CAI"], ["ZRH", "CMN"],
  ["VIE", "FCO"], ["VIE", "MXP"], ["VIE", "LIS"], ["VIE", "ATH"], ["VIE", "DUB"], ["VIE", "CPH"], ["VIE", "ARN"], ["VIE", "OSL"], ["VIE", "HEL"], ["VIE", "WAW"], ["VIE", "PRG"], ["VIE", "IST"],
  ["VIE", "DXB"], ["VIE", "AUH"], ["VIE", "DOH"], ["VIE", "RUH"], ["VIE", "JED"], ["VIE", "TLV"], ["VIE", "BKK"], ["VIE", "DEL"], ["VIE", "PVG"], ["VIE", "CAI"],
  ["FCO", "MXP"], ["FCO", "LIS"], ["FCO", "ATH"], ["FCO", "DUB"], ["FCO", "CPH"], ["FCO", "ARN"], ["FCO", "OSL"], ["FCO", "HEL"], ["FCO", "WAW"], ["FCO", "PRG"], ["FCO", "IST"], ["FCO", "MAN"],
  ["FCO", "DXB"], ["FCO", "AUH"], ["FCO", "DOH"], ["FCO", "RUH"], ["FCO", "JED"], ["FCO", "TLV"], ["FCO", "HND"], ["FCO", "ICN"], ["FCO", "BKK"], ["FCO", "DEL"], ["FCO", "PEK"], ["FCO", "PVG"],
  ["FCO", "CAI"], ["FCO", "CMN"], ["FCO", "ALG"], ["FCO", "TUN"], ["FCO", "ADD"],
  ["MXP", "LIS"], ["MXP", "ATH"], ["MXP", "DUB"], ["MXP", "CPH"], ["MXP", "ARN"], ["MXP", "OSL"], ["MXP", "HEL"], ["MXP", "WAW"], ["MXP", "PRG"], ["MXP", "IST"], ["MXP", "MAN"], ["MXP", "DXB"],
  ["MXP", "AUH"], ["MXP", "DOH"], ["MXP", "RUH"], ["MXP", "JED"], ["MXP", "TLV"], ["MXP", "SIN"], ["MXP", "HND"], ["MXP", "HKG"], ["MXP", "BKK"], ["MXP", "DEL"], ["MXP", "BOM"], ["MXP", "PVG"],
  ["MXP", "CAI"], ["MXP", "CMN"], ["MXP", "ALG"], ["MXP", "TUN"],
  ["LIS", "ATH"], ["LIS", "DUB"], ["LIS", "CPH"], ["LIS", "ARN"], ["LIS", "OSL"], ["LIS", "HEL"], ["LIS", "WAW"], ["LIS", "PRG"], ["LIS", "IST"], ["LIS", "MAN"], ["LIS", "DXB"], ["LIS", "DOH"],
  ["LIS", "TLV"], ["LIS", "CMN"], ["LIS", "ALG"], ["LIS", "TUN"], ["LIS", "CAI"], ["LIS", "DKR"],
  ["ATH", "DUB"], ["ATH", "CPH"], ["ATH", "ARN"], ["ATH", "OSL"], ["ATH", "HEL"], ["ATH", "WAW"], ["ATH", "PRG"], ["ATH", "IST"], ["ATH", "DXB"], ["ATH", "AUH"], ["ATH", "DOH"], ["ATH", "RUH"],
  ["ATH", "JED"], ["ATH", "TLV"], ["ATH", "SIN"], ["ATH", "CAI"], ["ATH", "CMN"], ["ATH", "ALG"], ["ATH", "TUN"],
  ["DUB", "CPH"], ["DUB", "ARN"], ["DUB", "OSL"], ["DUB", "HEL"], ["DUB", "WAW"], ["DUB", "PRG"], ["DUB", "IST"], ["DUB", "MAN"], ["DUB", "EDI"], ["DUB", "DXB"], ["DUB", "AUH"], ["DUB", "DOH"],
  ["DUB", "RUH"], ["DUB", "TLV"],
  ["CPH", "ARN"], ["CPH", "OSL"], ["CPH", "HEL"], ["CPH", "WAW"], ["CPH", "PRG"], ["CPH", "IST"], ["CPH", "DXB"], ["CPH", "DOH"], ["CPH", "BKK"], ["CPH", "SIN"], ["CPH", "HND"], ["CPH", "PVG"],
  ["CPH", "CAI"],
  ["ARN", "OSL"], ["ARN", "HEL"], ["ARN", "WAW"], ["ARN", "PRG"], ["ARN", "IST"], ["ARN", "DXB"], ["ARN", "DOH"], ["ARN", "BKK"],
  ["OSL", "HEL"], ["OSL", "WAW"], ["OSL", "PRG"], ["OSL", "IST"], ["OSL", "DXB"], ["OSL", "DOH"], ["OSL", "BKK"],
  ["HEL", "WAW"], ["HEL", "PRG"], ["HEL", "IST"], ["HEL", "DXB"], ["HEL", "DOH"], ["HEL", "HND"], ["HEL", "NRT"], ["HEL", "ICN"], ["HEL", "HKG"], ["HEL", "BKK"], ["HEL", "SIN"], ["HEL", "DEL"],
  ["HEL", "PVG"],
  ["WAW", "PRG"], ["WAW", "IST"], ["WAW", "DXB"], ["WAW", "DOH"], ["WAW", "RUH"], ["WAW", "TLV"], ["WAW", "NRT"], ["WAW", "ICN"], ["WAW", "PEK"], ["WAW", "DEL"], ["WAW", "BOM"],
  ["PRG", "IST"], ["PRG", "DXB"], ["PRG", "DOH"], ["PRG", "RUH"], ["PRG", "TLV"], ["PRG", "ICN"],
  ["IST", "DME"], ["IST", "DXB"], ["IST", "AUH"], ["IST", "DOH"], ["IST", "RUH"], ["IST", "JED"], ["IST", "TLV"], ["IST", "SIN"], ["IST", "HND"], ["IST", "NRT"], ["IST", "KIX"], ["IST", "ICN"],
  ["IST", "HKG"], ["IST", "TPE"], ["IST", "BKK"], ["IST", "KUL"], ["IST", "SGN"], ["IST", "HAN"], ["IST", "MNL"], ["IST", "CGK"], ["IST", "DPS"], ["IST", "DEL"], ["IST", "BOM"], ["IST", "PEK"],
  ["IST", "PVG"], ["IST", "JNB"], ["IST", "CPT"], ["IST", "NBO"], ["IST", "ADD"], ["IST", "CAI"], ["IST", "CMN"], ["IST", "ALG"], ["IST", "TUN"], ["IST", "LOS"], ["IST", "DKR"], ["IST", "SYD"],
  ["IST", "MEL"],
  ["DME", "DXB"], ["DME", "AUH"], ["DME", "DOH"], ["DME", "DEL"], ["DME", "PEK"], ["DME", "PVG"], ["DME", "BKK"], ["DME", "CAI"],

  // --- Conexiones de Medio Oriente ---
  ["DXB", "AUH"], ["DXB", "DOH"], ["DXB", "RUH"], ["DXB", "JED"], ["DXB", "TLV"], ["DXB", "SIN"], ["DXB", "HND"], ["DXB", "NRT"], ["DXB", "KIX"], ["DXB", "ICN"], ["DXB", "PEK"], ["DXB", "PVG"],
  ["DXB", "HKG"], ["DXB", "TPE"], ["DXB", "BKK"], ["DXB", "KUL"], ["DXB", "SGN"], ["DXB", "HAN"], ["DXB", "MNL"], ["DXB", "CGK"], ["DXB", "DPS"], ["DXB", "DEL"], ["DXB", "BOM"], ["DXB", "JNB"],
  ["DXB", "CPT"], ["DXB", "NBO"], ["DXB", "ADD"], ["DXB", "CAI"], ["DXB", "CMN"], ["DXB", "ALG"], ["DXB", "TUN"], ["DXB", "LOS"], ["DXB", "DKR"], ["DXB", "SYD"], ["DXB", "MEL"], ["DXB", "BNE"],
  ["DXB", "PER"], ["DXB", "AKL"],
  ["AUH", "DOH"], ["AUH", "RUH"], ["AUH", "JED"], ["AUH", "TLV"], ["AUH", "SIN"], ["AUH", "HND"], ["AUH", "ICN"], ["AUH", "PEK"], ["AUH", "PVG"], ["AUH", "HKG"], ["AUH", "BKK"], ["AUH", "KUL"],
  ["AUH", "MNL"], ["AUH", "CGK"], ["AUH", "DEL"], ["AUH", "BOM"], ["AUH", "JNB"], ["AUH", "CAI"], ["AUH", "CMN"], ["AUH", "SYD"], ["AUH", "MEL"],
  ["DOH", "RUH"], ["DOH", "JED"], ["DOH", "TLV"], ["DOH", "SIN"], ["DOH", "HND"], ["DOH", "NRT"], ["DOH", "KIX"], ["DOH", "ICN"], ["DOH", "PEK"], ["DOH", "PVG"], ["DOH", "HKG"], ["DOH", "BKK"],
  ["DOH", "KUL"], ["DOH", "SGN"], ["DOH", "HAN"], ["DOH", "MNL"], ["DOH", "CGK"], ["DOH", "DPS"], ["DOH", "DEL"], ["DOH", "BOM"], ["DOH", "JNB"], ["DOH", "CPT"], ["DOH", "NBO"], ["DOH", "ADD"],
  ["DOH", "CAI"], ["DOH", "CMN"], ["DOH", "ALG"], ["DOH", "TUN"], ["DOH", "LOS"], ["DOH", "SYD"], ["DOH", "MEL"], ["DOH", "BNE"], ["DOH", "PER"], ["DOH", "AKL"],
  ["RUH", "JED"], ["RUH", "CAI"], ["RUH", "CMN"], ["RUH", "DEL"], ["RUH", "BOM"], ["RUH", "SIN"], ["RUH", "MNL"], ["RUH", "BKK"],
  ["JED", "CAI"], ["JED", "CMN"], ["JED", "ALG"], ["JED", "TUN"], ["JED", "DEL"], ["JED", "BOM"], ["JED", "KUL"], ["JED", "CGK"], ["JED", "MNL"], ["JED", "LOS"], ["JED", "ADD"],
  ["TLV", "CAI"], ["TLV", "DEL"], ["TLV", "BKK"], ["TLV", "HKG"], ["TLV", "HND"],

  // --- Conexiones de Asia ---
  ["SIN", "HND"], ["SIN", "NRT"], ["SIN", "KIX"], ["SIN", "ICN"], ["SIN", "PEK"], ["SIN", "PVG"], ["SIN", "HKG"], ["SIN", "TPE"], ["SIN", "BKK"], ["SIN", "KUL"], ["SIN", "SGN"], ["SIN", "HAN"],
  ["SIN", "MNL"], ["SIN", "CGK"], ["SIN", "DPS"], ["SIN", "DEL"], ["SIN", "BOM"], ["SIN", "JNB"], ["SIN", "CPT"], ["SIN", "ADD"], ["SIN", "SYD"], ["SIN", "MEL"], ["SIN", "BNE"], ["SIN", "PER"],
  ["SIN", "AKL"],
  ["HND", "NRT"], ["HND", "KIX"], ["HND", "ICN"], ["HND", "PEK"], ["HND", "PVG"], ["HND", "HKG"], ["HND", "TPE"], ["HND", "BKK"], ["HND", "KUL"], ["HND", "SGN"], ["HND", "HAN"], ["HND", "MNL"],
  ["HND", "CGK"], ["HND", "DEL"], ["HND", "BOM"], ["HND", "SYD"], ["HND", "MEL"], ["HND", "BNE"], ["HND", "PER"], ["HND", "AKL"],
  ["NRT", "ICN"], ["NRT", "PEK"], ["NRT", "PVG"], ["NRT", "HKG"], ["NRT", "TPE"], ["NRT", "BKK"], ["NRT", "KUL"], ["NRT", "SGN"], ["NRT", "HAN"], ["NRT", "MNL"], ["NRT", "CGK"], ["NRT", "DPS"],
  ["NRT", "DEL"], ["NRT", "BOM"], ["NRT", "SYD"], ["NRT", "MEL"], ["NRT", "BNE"], ["NRT", "PER"], ["NRT", "AKL"],
  ["KIX", "ICN"], ["KIX", "PEK"], ["KIX", "PVG"], ["KIX", "HKG"], ["KIX", "TPE"], ["KIX", "BKK"], ["KIX", "KUL"], ["KIX", "SGN"], ["KIX", "MNL"], ["KIX", "SYD"], ["KIX", "MEL"],
  ["ICN", "PEK"], ["ICN", "PVG"], ["ICN", "HKG"], ["ICN", "TPE"], ["ICN", "BKK"], ["ICN", "KUL"], ["ICN", "SGN"], ["ICN", "HAN"], ["ICN", "MNL"], ["ICN", "CGK"], ["ICN", "DPS"], ["ICN", "DEL"],
  ["ICN", "BOM"], ["ICN", "SYD"], ["ICN", "MEL"], ["ICN", "BNE"], ["ICN", "AKL"],
  ["PEK", "PVG"], ["PEK", "HKG"], ["PEK", "TPE"], ["PEK", "BKK"], ["PEK", "KUL"], ["PEK", "SGN"], ["PEK", "HAN"], ["PEK", "MNL"], ["PEK", "CGK"], ["PEK", "DEL"], ["PEK", "BOM"], ["PEK", "JNB"],
  ["PEK", "ADD"], ["PEK", "CAI"], ["PEK", "SYD"], ["PEK", "MEL"], ["PEK", "BNE"], ["PEK", "AKL"],
  ["PVG", "HKG"], ["PVG", "TPE"], ["PVG", "BKK"], ["PVG", "KUL"], ["PVG", "SGN"], ["PVG", "HAN"], ["PVG", "MNL"], ["PVG", "CGK"], ["PVG", "DPS"], ["PVG", "DEL"], ["PVG", "BOM"], ["PVG", "ADD"],
  ["PVG", "CAI"], ["PVG", "SYD"], ["PVG", "MEL"], ["PVG", "BNE"], ["PVG", "AKL"],
  ["HKG", "TPE"], ["HKG", "BKK"], ["HKG", "KUL"], ["HKG", "SGN"], ["HKG", "HAN"], ["HKG", "MNL"], ["HKG", "CGK"], ["HKG", "DPS"], ["HKG", "DEL"], ["HKG", "BOM"], ["HKG", "JNB"], ["HKG", "ADD"],
  ["HKG", "SYD"], ["HKG", "MEL"], ["HKG", "BNE"], ["HKG", "PER"], ["HKG", "AKL"],
  ["TPE", "BKK"], ["TPE", "KUL"], ["TPE", "SGN"], ["TPE", "HAN"], ["TPE", "MNL"], ["TPE", "CGK"], ["TPE", "DPS"], ["TPE", "DEL"], ["TPE", "SYD"], ["TPE", "MEL"], ["TPE", "BNE"], ["TPE", "AKL"],
  ["BKK", "KUL"], ["BKK", "SGN"], ["BKK", "HAN"], ["BKK", "MNL"], ["BKK", "CGK"], ["BKK", "DPS"], ["BKK", "DEL"], ["BKK", "BOM"], ["BKK", "ADD"], ["BKK", "CAI"], ["BKK", "SYD"], ["BKK", "MEL"],
  ["BKK", "BNE"], ["BKK", "PER"], ["BKK", "AKL"],
  ["KUL", "SGN"], ["KUL", "HAN"], ["KUL", "MNL"], ["KUL", "CGK"], ["KUL", "DPS"], ["KUL", "DEL"], ["KUL", "BOM"], ["KUL", "ADD"], ["KUL", "SYD"], ["KUL", "MEL"], ["KUL", "BNE"], ["KUL", "PER"],
  ["KUL", "AKL"],
  ["SGN", "HAN"], ["SGN", "MNL"], ["SGN", "CGK"], ["SGN", "DPS"], ["SGN", "DEL"], ["SGN", "BOM"], ["SGN", "SYD"], ["SGN", "MEL"],
  ["HAN", "MNL"], ["HAN", "DEL"], ["HAN", "BOM"], ["HAN", "SYD"], ["HAN", "MEL"],
  ["MNL", "CGK"], ["MNL", "DPS"], ["MNL", "DEL"], ["MNL", "SYD"], ["MNL", "MEL"], ["MNL", "BNE"], ["MNL", "PER"],
  ["CGK", "DPS"], ["CGK", "DEL"], ["CGK", "SYD"], ["CGK", "MEL"], ["CGK", "PER"],
  ["DPS", "SYD"], ["DPS", "MEL"], ["DPS", "BNE"], ["DPS", "PER"], ["DPS", "AKL"],
  ["DEL", "BOM"], ["DEL", "ADD"], ["DEL", "CAI"], ["DEL", "SYD"], ["DEL", "MEL"],
  ["BOM", "ADD"], ["BOM", "CAI"],

  // --- Conexiones de África ---
  ["JNB", "CPT"], ["JNB", "NBO"], ["JNB", "ADD"], ["JNB", "CAI"], ["JNB", "LOS"], ["JNB", "PER"], ["JNB", "SYD"],
  ["CPT", "NBO"], ["CPT", "ADD"],
  ["NBO", "ADD"], ["NBO", "CAI"], ["NBO", "LOS"], ["NBO", "DKR"],
  ["ADD", "CAI"], ["ADD", "LOS"], ["ADD", "DKR"], ["ADD", "CMN"],
  ["CAI", "CMN"], ["CAI", "ALG"], ["CAI", "TUN"], ["CAI", "LOS"],
  ["CMN", "ALG"], ["CMN", "TUN"], ["CMN", "LOS"], ["CMN", "DKR"],
  ["ALG", "TUN"], ["ALG", "DKR"],
  ["TUN", "DKR"],
  ["LOS", "DKR"],

  // --- Conexiones de Oceanía ---
  ["SYD", "MEL"], ["SYD", "BNE"], ["SYD", "PER"], ["SYD", "AKL"],
  ["MEL", "BNE"], ["MEL", "PER"], ["MEL", "AKL"],
  ["BNE", "PER"], ["BNE", "AKL"],
  ["PER", "AKL"]
];
